---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: servers
  require_chef_for_busser: true
  require_ansible_repo: true
  ansible_version: latest

platforms:
  - name: centos-7.3

suites:
  - name: docker
    run_list:
    attributes:
