---
driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: servers
  require_chef_for_busser: true
  require_ansible_repo: true
  ansible_version: latest

platforms:
  - name: centos-7.3
    driver_config:
      platform: centos
      dockerfile: .kitchen-docker/centos7/Dockerfile
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

suites:
  - name: docker
    run_list:
    attributes:
